# Generated by Django 4.2.5 on 2023-09-05 11:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Age must be at least 10 years old.'), django.core.validators.MaxValueValidator(85, message='Age must be at most 85 years old.')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.FloatField()),
                ('cramps', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message="I don't have pain."), django.core.validators.MaxValueValidator(10, message='I have pain.')])),
                ('feeling_tired', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message="I don't have pain."), django.core.validators.MaxValueValidator(10, message='I have pain.')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('cycle_length', models.IntegerField(default=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
